### ISSUE TITLE
Cascade missing from Conda Package

### ISSUE THREAD

**Issue by 8bit-Dude** [projectchrono/chrono#249]
Hey Guys, 
I installed pyChrono on Miniconda3, but noticed that the Cascade module is missing.
I wonder why, since pythonOCC 0.7.4 is also available on conda.

Anyhow, what would be the fastest way to get the cascade module installed? (The documentation implies that recompiling the whole lot with Cmake is required. That is not very appealing...)

**Comment by Benatti1991** [comment]
Hi,
the conda package is available in the develop version of PyChrono. Please re-install using 
`conda install -c projectchrono/label/develop pychrono`
The support has been suspended due to some version conflict but now, as you correctly pointed out, every dependency is available on Anaconda.
Thanks,
Simone

**Comment by 8bit-Dude** [comment]
Thanks for the quick reply, I can confirm that moving to the development package fixed the issue! :-)
