### ISSUE TITLE
demo_FEA_contacts slower in v6 than v5

### ISSUE THREAD

**Issue by SoDeserts** [projectchrono/chrono#342]
Hello,
I am working on the comparison of demos between chrono v5.0.0 and v6.0.0 to understand some evolutions in order to migrate my code from v5 to v6. I am working on Mac Os Big Sur 11.6.

The demo FEA_contacts seemed to run quite slower on v6, so I timed each time step with ChTimer and in v5 it takes roughly 40-50 ms per step, while it takes around 90 ms per step in v6.

I compared the cpp files and, except for the change in the way contact materials are implemented in v6, the code is strictly the same.

Is it normal that the same demo will run significantly slower in v6 compared to v5 ? Am I the only one observing this ? 
Thanks a lot for any help on this.

**Comment by rserban** [comment]
@SoDeserts - this is due to the update to a newer version of the embedded Bullet library for collision detection.  We did notice some slight performance degradation in certain situations, but overall we decided the update was worth it.

Having said that, programs such as the one you mentioned (now named `demo_FEA_contacts_SMC`) require explicitly setting the different number of OpenMP threads with ChSystem::SetNumThreads.  I added this call to a couple of demos, but you may want to experiment with different values.
