### ISSUE TITLE
ChronoEngine Installation Issue on Ubuntu 23.10 with CMake 3.27.4: CHRONO_MPI_FOUND Variable Not Recognized in ChronoConfig.cmake

### ISSUE THREAD

**Issue by ghost** [projectchrono/chrono#472]
Hi. I'm having a specific problem on Ubuntu 23.10, cmake 3.27.4 when trying to install chronoengine through vcpkg. ChronoConfig.cmake, line 128 where `CHRONO_MPI_FOUND` is used as `${CHRONO_MPI_FOUND}` so I have to replace it. 
```
sed -i '128s/.*/if(Chrono_HAS_vehicle AND CHRONO_MPI_FOUND)/' /home/ubuntu/vcpkg/installed/x64-linux/share/chronoengine/ChronoConfig.cmake
```

**Comment by dariomangoni** [comment]
Hi @punowo,
on May 29th 2023 (at [this](60cb460b0c873f62e554129861923e04e589fb34) commit) we renamed the old _ChronoConfig.cmake_ into _chrono-config.cmake_.
Since your issue is quite recent, please double check that in your `<chrono source>/cmake` folder **only** the newest _chrono-config.cmake_ is there. If you find any _ChronoConfig.cmake_ please **delete** it!

I incurred in the same kind of problems some months ago!
