### ISSUE TITLE
How to add object after Render

### ISSUE THREAD

**Issue by zanxueyan** [projectchrono/chrono#484]
I want to be able to add objects to the scene again once the window is rendered, but I looked up the examples so far, which all load components to sys, execute the AttachSystem function, and finally render in a loop.
Could you please give a simple example for guidance? Thank you very much!

**Comment by rserban** [comment]
There are several demos that create objects dynamically during the simulation.  Search through the Chrono examples/demos for calls to `BindItem`.  This is a function that you will need to call for any objects you create after the initial processing of visualization assets in order to bind the object's visual assets to the current run-time visualization system.

On a different note: please post questions about Chrono *usage* to the forum (mailing list).  We'd like to reserve the GitHub Issues page for bug reports, feature requests, etc.
