### ISSUE TITLE
Vehicle module can't find this part of vehiclecosim

### ISSUE THREAD

**Issue by wyj1111kkk** [projectchrono/chrono#532]
Hi everyone! When I test template_project_vehicle_cosim inside chrono, it shows in cmake that the part vehiclecosim is not found. I have tried many times but still no solution, this problem has been bothering me for a long time, what is the reason for this?
![E7297751ABDCFCDBCF6699E9FB026431](https://github.com/user-attachments/assets/c4479b08-8b76-461c-8cd6-52f418044d80)

**Comment by rserban** [comment]
The reason is listed pretty clearly in the CMake output: your Chrono build was not configured with vehicle co-simulation support.
Go back to the Chrono CMake configuration and look carefully through the messages you get there.
The co-simulation support in Chrono::Vehicle **requires** MPI.  If an MPI installation is not found, then co-simulation support is disabled.
Once you get MPI installed, reconfigure and rebuild Chrono. Make sure you see that related demos are being built (they have names starting with `demo_VEH_Cosim_`.  After that, you should be able to correctly configure and build template_project_vehicle_cosim.

**Comment by wyj1111kkk** [comment]
I see, thanks a lot, problem solved!
